spring.application.name=backend
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/crud_api_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=VENU95@sha
spring.jpa.show-sql=true